version: '3'

services:

  frontend:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/usr/app
    ports:
      - '3000:3000'
